In [2]:
import numpy as np
import stock_exploration
import math

In [2]:
stocks = ["AAPL", "TSLA"]
start_date = "2020-06-01"
end_date = "2021-08-01"
trials = 3


In [3]:
train, test = stock_exploration.fetchStocks(stocks, start_date, end_date, 0.2, 0.05, show=False)

manyPaths = stock_exploration.brownianMotion_Cholesky(
    stocks, train, test.shape[0], trials, False, test
)

0.0020542951225415076 0.022585901136071722
0.005560619677201507 0.04652278475642288


In [ ]:
# for stockIndex, paths in enumerate(manyPaths):
#     compareToTest(
#         stocks[stockIndex],
#         paths.T,
#         test["adj_close_{}".format(stocks[stockIndex])].values,
#         0.95,
#         show=False,
#     )

#     # Get mean and st dev of log returns for predicted paths
#     mew, sigma = getSimulatedVals(paths)

In [4]:
manyPaths

array([[[129.66055298, 134.01286809, 128.7545309 , 130.64567831,
         127.76126383, 125.10926967, 119.21583642, 122.58475906,
         128.27629756, 129.55928368, 129.85147959, 129.17029815,
         129.51063077, 126.88654745, 124.72780528, 127.89957609,
         133.11356427, 138.54466461, 140.66988927, 138.65903654,
         134.52759453, 131.65352447, 132.25079151, 133.64228897,
         136.18586823, 133.72738659, 131.13307639, 130.72279964,
         136.4741458 , 137.04730551, 135.30222035, 136.71169897,
         137.42351019, 133.69540339, 134.5727818 , 136.9263622 ,
         139.34697176, 138.00955102, 140.16344187, 144.57740253,
         144.39746104, 145.17826579, 143.92403142, 141.65919681,
         148.01035429, 145.79859926, 143.30078157, 142.74101219,
         132.83380813, 138.91874354, 136.53253665, 140.2616924 ,
         140.45174825, 135.32854227, 137.10986306, 137.6374579 ,
         136.25602855, 135.80237482, 146.07115854],
        [129.66055298, 130.78027018, 1

In [44]:
manyPaths[0][0]

array([129.66055298, 134.01286809, 128.7545309 , 130.64567831,
       127.76126383, 125.10926967, 119.21583642, 122.58475906,
       128.27629756, 129.55928368, 129.85147959, 129.17029815,
       129.51063077, 126.88654745, 124.72780528, 127.89957609,
       133.11356427, 138.54466461, 140.66988927, 138.65903654,
       134.52759453, 131.65352447, 132.25079151, 133.64228897,
       136.18586823, 133.72738659, 131.13307639, 130.72279964,
       136.4741458 , 137.04730551, 135.30222035, 136.71169897,
       137.42351019, 133.69540339, 134.5727818 , 136.9263622 ,
       139.34697176, 138.00955102, 140.16344187, 144.57740253,
       144.39746104, 145.17826579, 143.92403142, 141.65919681,
       148.01035429, 145.79859926, 143.30078157, 142.74101219,
       132.83380813, 138.91874354, 136.53253665, 140.2616924 ,
       140.45174825, 135.32854227, 137.10986306, 137.6374579 ,
       136.25602855, 135.80237482, 146.07115854])

In [12]:
manyPaths[0][0].size

59

In [43]:
((math.exp(math.log(146.07) - math.log(129.66)) - 1) / manyPaths[0][0].size) * 252

0.5405689456387918

In [38]:
# Yearly return 54%
(((146.07 - 129.66) / 129.66) /  manyPaths[0][0].size) * 252

0.5405689456387893

In [51]:
((math.exp(np.sum(np.diff(np.log(manyPaths[0][0])))) - 1) / manyPaths[0][0].size) * 252

0.5405865882295042

In [52]:
for stockIndex, paths in enumerate(manyPaths):
    break

In [53]:
paths

array([[129.66055298, 134.01286809, 128.7545309 , 130.64567831,
        127.76126383, 125.10926967, 119.21583642, 122.58475906,
        128.27629756, 129.55928368, 129.85147959, 129.17029815,
        129.51063077, 126.88654745, 124.72780528, 127.89957609,
        133.11356427, 138.54466461, 140.66988927, 138.65903654,
        134.52759453, 131.65352447, 132.25079151, 133.64228897,
        136.18586823, 133.72738659, 131.13307639, 130.72279964,
        136.4741458 , 137.04730551, 135.30222035, 136.71169897,
        137.42351019, 133.69540339, 134.5727818 , 136.9263622 ,
        139.34697176, 138.00955102, 140.16344187, 144.57740253,
        144.39746104, 145.17826579, 143.92403142, 141.65919681,
        148.01035429, 145.79859926, 143.30078157, 142.74101219,
        132.83380813, 138.91874354, 136.53253665, 140.2616924 ,
        140.45174825, 135.32854227, 137.10986306, 137.6374579 ,
        136.25602855, 135.80237482, 146.07115854],
       [129.66055298, 130.78027018, 132.68159885, 131

In [60]:
np.log(paths)

array([[4.8649199 , 4.89793583, 4.85790773, 4.87248891, 4.8501634 ,
        4.82918751, 4.7809356 , 4.8088027 , 4.85418651, 4.86413857,
        4.86639133, 4.86113167, 4.86376297, 4.84329336, 4.82613381,
        4.85124539, 4.89120263, 4.93119276, 4.94641593, 4.93201795,
        4.90176934, 4.88017366, 4.88470006, 4.89516675, 4.91402063,
        4.8958033 , 4.87621266, 4.87307905, 4.91613519, 4.92032616,
        4.90751095, 4.91787432, 4.92306747, 4.8955641 , 4.90210518,
        4.91944328, 4.93696702, 4.92732289, 4.94280918, 4.97381502,
        4.97256964, 4.97796241, 4.9692856 , 4.95342415, 4.99728223,
        4.98222621, 4.96494579, 4.96103188, 4.88909878, 4.93388918,
        4.91656295, 4.94350991, 4.944864  , 4.90770547, 4.92078252,
        4.92462311, 4.91453568, 4.9112007 , 4.98409389],
       [4.8649199 , 4.87351859, 4.88795226, 4.88144547, 4.86619072,
        4.83047022, 4.79246276, 4.7938418 , 4.79733346, 4.801874  ,
        4.808392  , 4.80848716, 4.80770362, 4.76161097, 4.8

In [75]:
((math.exp(np.mean(np.sum(np.diff(np.log(paths)), axis=1))) - 1) / paths.shape[1]) * 252

0.4752115715307742

In [67]:
np.mean([0.11917399, 0.15732222, 0.03998692])

0.10549437666666667

In [73]:
paths.shape[1]

59

In [77]:
((math.exp(np.std(np.sum(np.diff(np.log(paths)), axis=1))) - 1) / paths.shape[1]) * 252

0.21391208052907823

In [76]:
stock_exploration.getSimulatedVals(paths)

[[129.66055298 134.01286809 128.7545309  130.64567831 127.76126383
  125.10926967 119.21583642 122.58475906 128.27629756 129.55928368
  129.85147959 129.17029815 129.51063077 126.88654745 124.72780528
  127.89957609 133.11356427 138.54466461 140.66988927 138.65903654
  134.52759453 131.65352447 132.25079151 133.64228897 136.18586823
  133.72738659 131.13307639 130.72279964 136.4741458  137.04730551
  135.30222035 136.71169897 137.42351019 133.69540339 134.5727818
  136.9263622  139.34697176 138.00955102 140.16344187 144.57740253
  144.39746104 145.17826579 143.92403142 141.65919681 148.01035429
  145.79859926 143.30078157 142.74101219 132.83380813 138.91874354
  136.53253665 140.2616924  140.45174825 135.32854227 137.10986306
  137.6374579  136.25602855 135.80237482 146.07115854]
 [129.66055298 130.78027018 132.68159885 131.82106924 129.82543208
  125.26985127 120.59800663 120.76443194 121.18683714 121.7383421
  122.5344232  122.54608446 122.45010188 116.93415119 122.17163437
  123.209

(0.0018188685095987633, 0.02230326409464921)

In [81]:
x= np.array([[-0.03743278, -0.00765455, -0.02033596],
 [-0.0216008,  -0.00575024, -0.01062089]])

In [95]:
x.shape

(2, 3)

In [99]:
((math.exp(np.mean(np.sum(x, axis=1))) - 1) / x.shape[1]) * 252

-4.232257864254962

In [87]:
(715.65401429 - 764.03997803) / 764.03997803

-0.06332909943372125

In [88]:
(735.57181571 - 764.03997803) / 764.03997803

-0.03726004284933141

In [92]:
(((-0.03726004284933141 + -0.06332909943372125) / 2) / 3) * 252

-4.224743975888211

In [3]:
y = np.array([0.00057776, 0.00065103, 0.0008128 ])

In [9]:
np.mean(y)

0.00068053

In [12]:
(math.exp(np.mean(y / 3)) -1) * 252

0.05717100418539367